(define-easy-handler (playerslist :uri (fmt "~A/playerslist" *ctxt*)) ()
  (page "Playerslist"
    (let ((plrs nil))
	(dolist (g *log-games1*)
	 (dolist (a (log-history g))
	    (if (> (length a) 1)
	     (pushnew (second a) plrs :test #'equal))))
    (dolist (p (sort  plrs #'string<))
      (a (:href (fmt "~A/player?name=~A" *ctxt* p)) p)
      (br))    )))