#+(not asdf)(load  "../../../../lispsystems/asdf")
(pushnew "../http/" asdf:*central-registry*)
(pushnew "../moje/" asdf:*central-registry*)
(pushnew "../../../../lispsystems/cl-store/" asdf:*central-registry*)
(pushnew "../../../../lispsystems/slime/" asdf:*central-registry*)
(pushnew "../../../../lispsystems/plain-odbc/trunk/" asdf:*central-registry*)
(pushnew "../../../../lispsystems/cffi/" asdf:*central-registry*)
(pushnew "../../../../lispsystems/s-xml/" asdf:*central-registry*)
(pushnew "../../../../lispsystems/cl-who/" asdf:*central-registry*)

